version: '3'

services:
    web:
        build: .
        ports:
            - 3000:80
        volumes:
            - ./app:/var/www/html
            - ./logs:/var/log
        networks:
            - default